# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mofo}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Wanstrath", "Jan Krutisch"]
  s.date = %q{2010-02-15}
  s.description = %q{mofo is a ruby microformat parser}
  s.email = %q{jan@krutisch.de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "CHANGELOG",
     "LICENSE",
     "Manifest.txt",
     "README",
     "Rakefile",
     "init.rb",
     "lib/microformat.rb",
     "lib/microformat/array.rb",
     "lib/microformat/object.rb",
     "lib/microformat/simple.rb",
     "lib/microformat/string.rb",
     "lib/microformat/time.rb",
     "lib/mofo.rb",
     "lib/mofo/adr.rb",
     "lib/mofo/geo.rb",
     "lib/mofo/hcalendar.rb",
     "lib/mofo/hcard.rb",
     "lib/mofo/hentry.rb",
     "lib/mofo/hfeed.rb",
     "lib/mofo/hresume.rb",
     "lib/mofo/hreview.rb",
     "lib/mofo/rel_bookmark.rb",
     "lib/mofo/rel_tag.rb",
     "lib/mofo/xfn.rb",
     "lib/mofo/xoxo.rb",
     "site/favicon.ico",
     "site/index.html",
     "site/mofo-logo.png",
     "site/mootools.v1.00.js",
     "site/p.js",
     "site/spinner.gif",
     "site/style.css",
     "site/try.html",
     "site/try/index.html",
     "site/try/p.js",
     "site/try/spinner.gif",
     "site/try/template.html",
     "site/try/trymofo.rb",
     "test/base_url_test.rb",
     "test/ext_test.rb",
     "test/fixtures/bob.html",
     "test/fixtures/chowhound.html",
     "test/fixtures/corkd.html",
     "test/fixtures/event_addr.html",
     "test/fixtures/events.html",
     "test/fixtures/fake.html",
     "test/fixtures/fauxtank.html",
     "test/fixtures/hatom.html",
     "test/fixtures/hatom_without_author.html",
     "test/fixtures/hresume.html",
     "test/fixtures/include_pattern_single_attribute.html",
     "test/fixtures/redflavor.html",
     "test/fixtures/simple.html",
     "test/fixtures/stoneship.html",
     "test/fixtures/upcoming.html",
     "test/fixtures/upcoming_single.html",
     "test/fixtures/xfn.html",
     "test/hatom_test.rb",
     "test/hcalendar_test.rb",
     "test/hcard_test.rb",
     "test/hresume_test.rb",
     "test/hreview_test.rb",
     "test/include_pattern_test.rb",
     "test/reltag_test.rb",
     "test/subclass_test.rb",
     "test/test_helper.rb",
     "test/xfn_test.rb",
     "test/xoxo_test.rb"
  ]
  s.homepage = %q{http://github.com/halfbyte/mofo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{mofo is a ruby microformat parser}
  s.test_files = [
    "test/base_url_test.rb",
     "test/ext_test.rb",
     "test/hatom_test.rb",
     "test/hcalendar_test.rb",
     "test/hcard_test.rb",
     "test/hresume_test.rb",
     "test/hreview_test.rb",
     "test/include_pattern_test.rb",
     "test/reltag_test.rb",
     "test/subclass_test.rb",
     "test/xfn_test.rb",
     "test/xoxo_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

